### PR TITLE
Server shouldn't send ping to client

### PR DESCRIPTION
**Pull request by michaelyou**
as the socket.io protocol shows: client send ping and server answer
pong.

The implement makes server send a ping to client pinginterval time after
server receive the ping, but the client send ping every pinginterval.
use chrome debug tool, you will find the server will response a ping and
a pong to the client's ping.

image

### CODE REVIEW

**Comment by erkie** [comment]
@googollee did you add this ping because it is needed for an old version of the Socket.io protocol? @michaelyou have you tested this with earlier versions of the socket.io client library? Noting that the master branch supports 0.9 if i recall correctly.

Also, this code does not compile:

```
# vendor/github.com/googollee/go-engine.io
./server_conn.go:366:3: tryDiff declared and not used
```

**Comment by googollee** [comment]
I remembered that when I did v0.9 branch, socket.io didn't have a well
definition about how to do ping between server and client.

**Comment by michaelyou** [comment]
@erkie sorry about the compile error and it is now fixed.

I didn't test it with eariler version. But ping from both client and server doesn't make sense.

**Comment by erkie** [comment]
@googollee I tried in production with our setup and got loads of `panic: close of closed channel`. on this line: https://github.com/googollee/go-engine.io/blob/b7e0b54ea52513ac58faa867f466ec09bfb21165/server_conn.go#L372

Do you think it's related to this error? https://github.com/googollee/go-engine.io/issues/47

There seems to problems with race conditions on the `serverConn.Close` method. We're getting this error at least once every day so I'd love to know your thoughts.

**Comment by googollee** [comment]
master was updated to v1.4. Please re-pr based on the new code.

**Pull request closed without merging**
