### PR TITLE
bugfix for read/write locker conflict

### PR DESCRIPTION
**Pull request by ardingchen**
#70 bugfix for read/write locker conflict

### CODE REVIEW

**Comment by erkie** [comment]
@ardingchen I recently merged a similar fix (albeit simpler) that might fix this issue. Could you give it a try? Thanks!

**Comment by HelloFy** [comment]
@erkie can you release this bug fix？

**Comment by erkie** [comment]
@hellofy like a tagged version release on this repo?

**Comment by chappjc** [comment]
While this PR addresses a legit issue with using a lock for two conflicting purposes, potentially resulting in a panic (rather than a deadlock which was the issue recently resolved by a new write lock approach in the `wrapper` type), I believe it would be fundamentally better to use a different mutex for the websocket's read methods than is used to protect `session.conn` and `session.transport`.  i.e. https://github.com/googollee/go-engine.io/pull/78/files#r326880910

However, given the locking going on in `wrapper`, the locking in the `util.go` types (`reader` and `writer`) is superfluous.  Please consider the alternative solution in PR https://github.com/googollee/go-engine.io/pull/78.

**Comment by googollee** [comment]
archived.

**Pull request closed without merging**
