### PR TITLE
added feature to allow custom connection id generator

### PR DESCRIPTION
**Pull request by fujimoto**
let suggest enabling custom connection id generator. this will make go-socket.io 1.x compatible to 0.9.

### CODE REVIEW

**Comment by googollee** [comment]
IMO, 0.9 package encoding doesn't compatible with 1.x. Do you test it with old version?

**Comment by fujimoto** [comment]
uhm, I've just thought that some people want to generate custom session id, not any more (so, I do not care about specific encoding implementation, it should be up to each developer).

(of course I know that most of developers will use default (current) newId(), but for some reason I just needed to add some other rules to connection id generator).

...does this make sense?

**Comment by fujimoto** [comment]
@googollee thanks! greatly appreciated.

**Comment by googollee** [comment]
@fujimoto I changed a little bit of your code, which set `newId` as default generator and will be overwrite by `SetNewId`.

And thank you for your feature.

**Pull request merged**
