### PR TITLE
remove ability to send pings from server

### PR DESCRIPTION
**Pull request by cedi**
This violated the protocol.
Only clients can send a ping to the server. Not the Server to the client.
This caused, that the client never responds to the ping and the server then disconnects the client.

### CODE REVIEW

**Comment by cedi** [comment]
Hey @erkie,
i will hack something as an example together with my college as soon he's back in the office. Unfortunately i'm no JS developer :sweat_smile: 

IMHO this should be quite easy to reproduce, if you setup an JS client which connects to the socket.io server implemented in go and you keep the connection open for some time. Then you should be able to see, that the Server disconnects the client, because of the timeout.

>  Is it using any particular version of Socket.io JS? 

Yes, i'm using version 2.0. I have no information about previous versions.

**Comment by erkie** [comment]
@cedi AFAIK this library supports an older version of the socket.io standard, and 2.0 is way too "new". @googollee might know which version specifically?

**Comment by googollee** [comment]
The master branch is v0.9 and there is v1.4 branch. I didn't verify with v2.0.

**Comment by googollee** [comment]
Master was updated to v1.4. Please re-pr based on the new code.

**Pull request closed without merging**
