### PR TITLE
Add optional write timeout for use with SetWriteDeadline to stop goro…

### PR DESCRIPTION
**Pull request by party79**
…utines sitting in iowait

### CODE REVIEW

**Comment by party79** [comment]
This is re https://github.com/googollee/go-socket.io/issues/152

**Comment by googollee** [comment]
Will you review the v1.4 branch to check if it meet your requirement?

**Comment by party79** [comment]
Oh, I didn't notice that, tried searching on github for SetWriteDeadline with that branch selected and didn't see it, it should as my issue is with writes getting stuck for a long time in io wait (causing deadlocks upstream) which SetWriteDeadline should stop

**Comment by googollee** [comment]
I know the issue very tough.

When I finish the work of new version go-socket.io, I will back to review this pr to see if it's OK. New version of go-engine.io can be got from gopkg.in/googollee/go-engine.io.v1. And I will leave master branch as old version to maintain compatible.

**Pull request closed without merging**
